baseline: rollout
baseline_kwargs: {}
batch_size: 64
data_dir: data/
dataloader_num_workers: 0
generate_default_data: false
log_on_step: true
lr_scheduler: null
lr_scheduler_interval: epoch
lr_scheduler_kwargs:
  gamma: 0.1
  milestones:
  - 80
  - 95
lr_scheduler_monitor: val/reward
metrics: {}
optimizer: Adam
optimizer_kwargs:
  lr: 0.0001
reward_scale: null
shuffle_train_dataloader: false
test_batch_size: null
test_data_size: 10000
train_data_size: 90000
val_batch_size: null
val_data_size: 10000
